### ISSUE TITLE
Exception for some images

### ISSUE THREAD

**Issue by Pramod07777** [robojamison/pycropper#1]
It works great for some images I am specifically doing for scanned documents.I got following exception and tell me what is wrong with images.

Searching for top edge...
Traceback (most recent call last):
  File "cropper.py", line 175, in <module>
    main()
  File "cropper.py", line 172, in main
    process(file_path)
  File "cropper.py", line 66, in process
    if not is_like_bg_color(pixel_map[i, y]):
  File "cropper.py", line 26, in is_like_bg_color
    bg_r, bg_g, bg_b = bg_color[0], bg_color[1], bg_color[2]
IndexError: tuple index out of range

**Comment by jamisonbryant** [comment]
Unfortunately, I am unable to diagnose and fix this issue because I cannot recreate the issue using the images you are using. I do not accept test images from users for security reasons. If you can find images in the PUBLIC DOMAIN (e.g. on Google Images) that cause the issue that you reported, then open another issue with the links to the images in the comments and I will take a look. Thank you for understanding.
